### PR TITLE
Db

### PR DESCRIPTION
**Pull request by esmason**

### CODE REVIEW

**Comment by nickspeal** [comment]
I cherrypicked out some of the first changes into dedicated PRs: #11 and #12.

This branch still contains functionality to save artist URIs to a database, but I think this PR should be refactored to only include the changes necessary to add that functionality.

BTW, please be careful about indentation levels. I see a couple cases of incorrect indentation. If you use the PyCharm IDE, it'll highlight them very loudly.

Finally, I'm not sure the `(artistURI, isInDB)` tuple is the most elegant way to structure this.

What about the following?

Rename `filter_artist()` to `get_artist_uri()`, which first checks for a database entry with the matching artist name. If it exists, short circuit and return, if it doesn't exist then search Spotify. After searching Spotify, add either None or the URI to the database for that artist's name so that next time we can check the DB to know whether the artist exists or not and what the URI is.

Also, let's make sure that Travis can test this as a part of the same PR. I have a hunch that we might need to add `python manage.py migrate` to the `.travis.yml` file as a part of the install step. That'll probably ensure that the database is using the most up-to-date schema.

**Comment by esmason** [comment]
This sounds good I agree that's a good way to structure it, was trying to wedge db lookup into the existing architecture but your way is better. Good idea about saving None so we don't lookup any artists unnecessarily on spotify. 
I've changed stuff on db to make tests work with new return types, but now I'll have to change it all back. Plus there are new changes by you and luc. Would it make sense just to close this PR (and the db branch), I'll make a new branch from staging and add the changes to models and spotipyHandler ?

**Comment by nickspeal** [comment]
PRs #11 and #12 should be ready for merge. I'll merge them now. I _think_ that those changes should be independent of what you're doing here so the order of merging shouldn't matter.

But in any case you can create a new branch off of staging or rebase this branch onto staging to sync them up.

**Comment by esmason** [comment]
for reference I made the changes suggested above by nick, to integrated database lookup to the new branch (database) but did not change the name of filter_artist , so as to keep the api the same (for testing etc.)

**Comment by nickspeal** [comment]
I think this PR is entirely superseded by #15, correct? If so, @esmason can you please close this PR and delete this branch?

**Comment by esmason** [comment]
correct and done

**Pull request closed without merging**
